name = "Heptapus"
uuid = "183adbe4-4102-11e9-3643-8738063a1e9c"
authors = ["Lucas C Wilcox <lucas@swirlee.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDAdrv = "c5f51814-7f29-56b8-a69c-e4d8f6be1fde"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
