[deps]
CUDAdrv = "c5f51814-7f29-56b8-a69c-e4d8f6be1fde"
CUDAnative = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
